### ISSUE TITLE
produce -> generateDate bug (I guess)

### ISSUE THREAD

**Issue by i1skn** [squeeks/glossy#35]
``` javascript
    // Line 363, produce.js

    if(dateObject.getTimezoneOffset() < 0) {
        // Ahead of UTC
        timeOffset = '+' + leadZero(hours) + '' + ':' + leadZero(minutes);
    } else if(dateObject.getTimezoneOffset() > 0) {
        // Behind UTC
        timeOffset = '-' + leadZero(hours) + '' + ':' + leadZero(minutes);
    } else {
        // UTC
        timeOffset = 'Z';
    }
```

Here we detect timezone offset. But after we use everywhere UTC date. 

``` javascript
    formattedDate = dateObject.getUTCFullYear()         + '-' +
    // N.B. Javascript Date objects return months of the year indexed from
    // zero, while the RFC 5424 syslog standard expects months indexed from
    // one.
    leadZero(dateObject.getUTCMonth() + 1)  + '-' +
    // N.B. Javascript Date objects return days of the month indexed from one
    // (unlike months of year), so this does not need any correction.
    leadZero(dateObject.getUTCDate())   + 'T' +
    // Time
    leadZero(dateObject.getUTCHours())         + ':' +
    leadZero(dateObject.getUTCMinutes())       + ':' +
    leadZero(dateObject.getUTCSeconds())       + '.' +
    leadZero(dateObject.getUTCMilliseconds())  +
    timeOffset;

    return formattedDate;
```

So, for example, now I have 16:00:00+01:00. Which mean that UTC time will be 15:00:00+00:00.
But if we follow algorithm above, we firstly get offset "+01:00" and after got time "15:00:00" and result would be "15:00:00+01:00", which is wrong...

**Comment by pavkriz** [comment]
Timestamp produced by the glossy producer: 2016-09-09T09:39:03.713+02:00

Timestamp produced by `date  --rfc-3339=s` : 2016-09-09 11:39:07+02:00

This is really an issue. @squeeks, please merge the pullrequest #34.

**Comment by pavkriz** [comment]
Actually an implementation what will send local time + correct timezone according to RFC3339 would be better (in contrast to pull request #34 that sends time in UTC).

**Comment by InfinitiesLoop** [comment]
Just lost an hour on this issue. Thought there was something wrong with my code that is processing log messages. Traced it back to the source software that uses this package. A fix would be greatly appreciated :)

**Comment by pavkriz** [comment]
Here's the fix I made https://github.com/pavkriz/glossy/commit/d6293cadac63949fd914980e648721f45a590e7d for my purposes.

**Comment by squeeks** [comment]
This is fixed.
